{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "soat-tech-challenge.fullname" . }}-ingress
  labels:
    {{- include "soat-tech-challenge.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "soat-tech-challenge.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
{{- end }}