loadtest:
  name: soat-tech-challenge-loadtest
  locust_locustfile_configmap: locust-scripts
  locust_host: http://soat-tech-challenge.fiap.svc.cluster.local:3000

master:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

worker:
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

service:
  type: ClusterIP
  port: 8089